#!/bin/bash
#
# License: BSD
#
# This script starts multiple ROS master, each of them containing a few nodes needed to simulate a robot.
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..
ROBOTS=${$1:+1}

# check that redis service is running
service redis-server status
REDIS_STATUS=$?

# starting the gardener
python -tt -m gardener --screen

if [ 0 -eq REDIS_STATUS ]; then
    echo "Starting $ROBOTS vegebots"
    for r in `seq 1 $ROBOTS`;
    do
        x-terminal-emulator -e roslaunch rostful_examples vegebot.launch --screen
    done
else
    echo "REDIS SERVER not running. Please start the service with : 'sudo service redis-server start'"
fi

