#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $*

#necessary to handle Flask Script arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -h|--host)
    HOST="$2"
    shift 2
    ;;
    -p|--port)
    PORT="$2"
    shift 2
    ;;
    --no-worker)
    WORKER="--no_worker"
    shift 1
    ;;
    -b|--broker-url)
    BROKER="$2"
    shift 2
    ;;
    -t|--worker-tasks)
    TASKS="$2"
    shift 2
    ;;
    __*)
    ROSARGS="${ROSARGS:+$ROSARGS }$key"
    #ros option
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option"
    shift 1
    ;;
esac
done

HOST=${HOST:+"-h $HOST"}
PORT=${PORT:+"-p $PORT"}
BROKER=${BROKER:+"-b $BROKER"}
TASKS=${TASKS:+"-t $TASKS"}
ROSARGS=${ROSARGS:+"--ros_args=$ROSARGS"}

set -x

python -tt -m rostful flask ${HOST} ${PORT} ${BROKER} ${WORKER} ${TASKS} "${ROSARGS}"

