#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

echo $*

#necessary to handle Click arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    --conf)
    CONF="$2"
    shift 2
    ;;
    --config)
    CONFIG="$2"
    shift 2
    ;;
    -b|--broker-url)
    BROKER="$2"
    shift 2
    ;;
    -t|--worker-tasks)
    TASKS="$2"
    shift 2
    ;;
    __*)
    ROSARGS="${ROSARGS:+$ROSARGS }$key"
    #ros option
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option"
    shift 1
    ;;
esac
done

CONF=${CONF:+"--conf=$CONF"}
CONFIG=${CONFIG:+"--config=$CONFIG"}
BROKER=${BROKER:+"-b $BROKER"}
TASKS=${TASKS:+"-A $TASKS"}
ROSARGS=${ROSARGS:+"--ros_args=$ROSARGS"}

set -x

# need to call python to use the flask-ext-catkin version accessible after  "source <devel|install>/setup.bash"
python -tt -m flower ${CONF} ${CONFIG} ${BROKER} ${TASKS} "${ROSARGS}"

