#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

echo $*

#necessary to handle Click arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    __*)
    ROSARGS="${ROSARGS:+$ROSARGS }$key"
    #ros option
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option"
    shift 1
    ;;
esac
done

ROSARGS=${ROSARGS:+"--ros_args=$ROSARGS"}

set -x

python -tt -m vegebot ${ROSARGS:+"$ROSARGS"}

