#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $*

#necessary to handle Flask Script arguments ( since ros doesnt pass it s argument in a standard/readline way )
while [[ $# > 0 ]]
do
key="$1"
case $key in
    -h|--host)
    HOST="$2"
    shift 2
    ;;
    -p|--port)
    PORT="$2"
    shift 2
    ;;
    -s|--server)
    SERVER="$2"
    shift 2
    ;;
    -c|--config)
    CONFIG="$2"
    shift 2
    ;;
    __*)  # matching basic ros args
    ROSARGS="${ROSARGS:+$ROSARGS} --ros-arg=$key"
    #ros option (multiple)
    shift 1
    ;;
    ~*)  # matching relative remapping ros args
    ROSARGS="${ROSARGS:+$ROSARGS} --ros-arg=$key"
    #ros option (multiple)
    shift 1
    ;;
    *)
    # unknown option
    echo "Unknown Option"
    shift 1
    ;;
esac
done

HOST=${HOST:+"-h $HOST"}
PORT=${PORT:+"-p $PORT"}
SERVER=${SERVER:+"-s $SERVER"}
CONFIG=${CONFIG:+"-c CONFIG"}

set -x

python -tt -m rostful run ${HOST} ${PORT} ${SERVER} ${CONFIG} ${ROSARGS}

