#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#forcing the current working directory to our parent
cd "$DIR"/..

# TODO : find a way to pass rosargs properly, without having to redefine all other params
python -tt -m rostful $*