#!/usr/bin/env python
import sys
import os
import click
import optparse
import rester
import time

# remove ROS arguments when launched as node (from rostest for exemple)
#@click.command(context_settings=dict(
#    ignore_unknown_options=True,
#))
#@click.option('--log', default='INFO', help='log help')
#@click.option('--tc', help='tc help')
#@click.option('--ts', help='ts help')
#@click.argument('unknown_args', nargs=-1, type=click.UNPROCESSED)
def roster():  #log, tc, ts, unknown_args):
    """A wrapper around Rester's cli runner that ignores unexpected arguments."""
    #specific rostest soution waiting for click fix
    print ("CWD : {cwd}".format(cwd=os.getcwd()))
    sys.argv = [a for a in sys.argv if not (a.startswith('__') or a.startswith('--gtest') or a.startswith('--text'))]
    print ("Rester ARGV : {argv}".format(argv=sys.argv))

    # sleeping a bit to let the server wake up for testing
    time.sleep(5)

    rester.apirunner.run()

if __name__ == '__main__':
    roster()

